import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import connectDB from '../config/db.js';

import User from '../models/User.js';
import ArtisanProfile from '../models/ArtisanProfile.js';
import Badge from '../models/Badge.js';
import Product from '../models/Product.js';
import CraftCollection from '../models/CraftCollection.js';
import OriginStory from '../models/OriginStory.js';
import Order from '../models/Order.js';
import Review from '../models/Review.js';
import WorkshopSession from '../models/WorkshopSession.js';
import WorkshopBooking from '../models/WorkshopBooking.js';

await connectDB();

await Promise.all([
    User.deleteMany(),
    ArtisanProfile.deleteMany(),
    Badge.deleteMany(),
    Product.deleteMany(),
    CraftCollection.deleteMany(),
    OriginStory.deleteMany(),
    Order.deleteMany(),
    Review.deleteMany(),
    WorkshopSession.deleteMany(),
    WorkshopBooking.deleteMany(),
]);

const hashedPassword = await bcrypt.hash('Password123!', 12);

const [adminUser, customer1, customer2, artisanUser1, artisanUser2, artisanUser3] =
    await User.insertMany([
        {
            name: 'Admin SouqJo',
            email: 'admin@souqjo.com',
            password: hashedPassword,
            role: 'admin',
            isEmailVerified: true,
            address: { city: 'Amman', governorate: 'Amman', country: 'Jordan' },
        },
        {
            name: 'Lara Khalid',
            email: 'lara@example.com',
            password: hashedPassword,
            role: 'customer',
            isEmailVerified: true,
            phone: '0791234567',
            address: { city: 'Amman', governorate: 'Amman', country: 'Jordan' },
        },
        {
            name: 'Omar Nasser',
            email: 'omar@example.com',
            password: hashedPassword,
            role: 'customer',
            isEmailVerified: true,
            phone: '0797654321',
            address: { city: 'Irbid', governorate: 'Irbid', country: 'Jordan' },
        },
        {
            name: 'Fatima Al-Rashid',
            email: 'fatima@example.com',
            password: hashedPassword,
            role: 'artisan',
            isEmailVerified: true,
            phone: '0795551111',
            address: { city: 'Amman', governorate: 'Amman', country: 'Jordan' },
        },
        {
            name: 'Khalil Mansour',
            email: 'khalil@example.com',
            password: hashedPassword,
            role: 'artisan',
            isEmailVerified: true,
            phone: '0795552222',
            address: { city: 'Madaba', governorate: 'Madaba', country: 'Jordan' },
        },
        {
            name: 'Nour Al-Jaber',
            email: 'nour@example.com',
            password: hashedPassword,
            role: 'artisan',
            isEmailVerified: true,
            phone: '0795553333',
            address: { city: 'Karak', governorate: 'Karak', country: 'Jordan' },
        },
    ]);

const [verifiedBadge, topSellerBadge, masterCraftsmanBadge, communityBadge] =
    await Badge.insertMany([
        {
            nameEn: 'Verified Artisan',
            nameAr: 'Verified Artisan',
            icon: 'verified',
            description: 'This artisan has been verified by SouqJo.',
            criteria: 'Submit valid ID and craft documentation.',
            badgeType: 'verification',
        },
        {
            nameEn: 'Top Seller',
            nameAr: 'Top Seller',
            icon: 'star',
            description: 'Achieved 50+ completed orders.',
            criteria: 'Complete 50 or more orders.',
            badgeType: 'milestone',
        },
        {
            nameEn: 'Master Craftsman',
            nameAr: 'Master Craftsman',
            icon: 'trophy',
            description: 'Recognized for exceptional craft quality.',
            criteria: 'Maintain a rating of 4.8+ across 20 reviews.',
            badgeType: 'achievement',
        },
        {
            nameEn: 'Community Builder',
            nameAr: 'Community Builder',
            icon: 'heart',
            description: 'Hosted 5+ workshops for the community.',
            criteria: 'Host and complete 5 workshops.',
            badgeType: 'special',
        },
    ]);

const [artisan1, artisan2, artisan3] = await ArtisanProfile.insertMany([
    {
        user: artisanUser1._id,
        craftName: 'Fatima Pottery Studio',
        bio: 'A passionate ceramics artist from Amman with over 15 years of experience. I specialize in traditional Jordanian pottery infused with contemporary design.',
        region: 'عمّان',
        specialties: ['Pottery', 'Ceramics', 'Glazing'],
        profileImage: 'https://placehold.co/400x400?text=Fatima',
        coverImage: 'https://placehold.co/1200x400?text=Fatima+Studio',
        socialLinks: {
            instagram: 'https://instagram.com/fatima.pottery',
            facebook: 'https://facebook.com/fatima.pottery',
        },
        yearsOfExperience: 15,
        isVerified: true,
        verifiedAt: new Date(),
        badges: [verifiedBadge._id, masterCraftsmanBadge._id],
        acceptsCustomOrders: true,
        acceptsWorkshops: true,
        rating: 4.9,
        reviewCount: 34,
        totalSales: 87,
        totalRevenue: 4350,
    },
    {
        user: artisanUser2._id,
        craftName: 'Khalil Wood & Mosaic',
        bio: 'A third-generation woodworker and mosaic artist based in Madaba. My work blends Byzantine mosaic traditions with modern Jordanian aesthetics.',
        region: 'مأدبا',
        specialties: ['Woodwork', 'Mosaic', 'Inlay'],
        profileImage: 'https://placehold.co/400x400?text=Khalil',
        coverImage: 'https://placehold.co/1200x400?text=Khalil+Workshop',
        socialLinks: {
            instagram: 'https://instagram.com/khalil.woodmosaic',
            whatsapp: '00962795552222',
        },
        yearsOfExperience: 22,
        isVerified: true,
        verifiedAt: new Date(),
        badges: [verifiedBadge._id, topSellerBadge._id],
        acceptsCustomOrders: true,
        acceptsWorkshops: false,
        rating: 4.7,
        reviewCount: 28,
        totalSales: 112,
        totalRevenue: 8960,
    },
    {
        user: artisanUser3._id,
        craftName: 'Nour Embroidery House',
        bio: 'Keeping the art of Palestinian and Jordanian embroidery alive. Each piece I create tells a story of heritage, identity, and feminine strength.',
        region: 'الكرك',
        specialties: ['Embroidery', 'Weaving', 'Textile Art'],
        profileImage: 'https://placehold.co/400x400?text=Nour',
        coverImage: 'https://placehold.co/1200x400?text=Nour+Embroidery',
        socialLinks: {
            facebook: 'https://facebook.com/nour.embroidery',
            whatsapp: '00962795553333',
        },
        yearsOfExperience: 10,
        isVerified: false,
        badges: [communityBadge._id],
        acceptsCustomOrders: true,
        acceptsWorkshops: true,
        rating: 4.5,
        reviewCount: 12,
        totalSales: 41,
        totalRevenue: 1845,
    },
]);

const [collection1, collection2, collection3] = await CraftCollection.insertMany([
    {
        artisan: artisan1._id,
        name: 'Earth Tones Collection',
        nameAr: 'Earth Tones Collection',
        description: 'A series of handcrafted ceramic pieces inspired by the earthy colors of the Jordanian desert.',
        coverImage: 'https://placehold.co/800x400?text=Earth+Tones',
        isActive: true,
        productCount: 2,
    },
    {
        artisan: artisan2._id,
        name: 'Madaba Mosaic Series',
        nameAr: 'Madaba Mosaic Series',
        description: 'Mosaic art pieces inspired by the famous Madaba Map and Byzantine heritage.',
        coverImage: 'https://placehold.co/800x400?text=Madaba+Mosaic',
        isActive: true,
        productCount: 2,
    },
    {
        artisan: artisan3._id,
        name: 'Heritage Stitch',
        nameAr: 'Heritage Stitch',
        description: 'Traditional embroidery patterns passed down through generations of Jordanian women.',
        coverImage: 'https://placehold.co/800x400?text=Heritage+Stitch',
        isActive: true,
        productCount: 1,
    },
]);

const [p1, p2, p3, p4, p5, p6] = await Product.insertMany([
    {
        artisan: artisan1._id,
        collectionId: collection1._id,
        title: 'Handmade Desert Clay Bowl',
        description: 'A beautiful hand-thrown clay bowl inspired by the warm tones of the Jordanian desert. Perfect for home decor or serving dried fruit.',
        price: 28,
        category: 'فخار وخزف',
        tags: ['pottery', 'clay', 'bowl', 'handmade', 'jordan'],
        images: ['https://placehold.co/600x600?text=Clay+Bowl'],
        thumbnailIndex: 0,
        productType: 'ready-made',
        stock: 8,
        materials: ['Clay', 'Natural Glaze'],
        dimensions: { width: 20, height: 10, depth: 20 },
        weight: 0.6,
        allowsCustomization: true,
        customizationOptions: {
            colors: ['Terracotta', 'Sand', 'Ivory'],
            engravingAllowed: true,
            maxCharsEngraving: 30,
            notes: 'Custom color glazing available upon request.',
        },
        isActive: true,
        isFeatured: true,
        rating: 4.9,
        reviewCount: 12,
        salesCount: 24,
        viewCount: 340,
    },
    {
        artisan: artisan1._id,
        collectionId: collection1._id,
        title: 'Ceramic Espresso Cup Set',
        description: 'Set of 4 handcrafted espresso cups with earthy glazes. Each cup is unique with slight variations that showcase the handmade nature of the craft.',
        price: 45,
        category: 'فخار وخزف',
        tags: ['cup', 'espresso', 'ceramic', 'set', 'coffee'],
        images: ['https://placehold.co/600x600?text=Espresso+Set'],
        thumbnailIndex: 0,
        productType: 'ready-made',
        stock: 5,
        materials: ['Stoneware', 'Lead-free Glaze'],
        dimensions: { width: 7, height: 6, depth: 7 },
        weight: 0.8,
        allowsCustomization: false,
        isActive: true,
        isFeatured: false,
        rating: 4.8,
        reviewCount: 9,
        salesCount: 18,
        viewCount: 210,
    },
    {
        artisan: artisan2._id,
        collectionId: collection2._id,
        title: 'Madaba Map Mosaic Panel',
        description: 'A handcrafted mosaic panel recreating a section of the famous 6th-century Madaba Map. Made with authentic Byzantine-style glass tesserae.',
        price: 185,
        category: 'فسيفساء',
        tags: ['mosaic', 'madaba', 'map', 'byzantine', 'wall-art'],
        images: ['https://placehold.co/600x600?text=Madaba+Mosaic'],
        thumbnailIndex: 0,
        productType: 'made-to-order',
        leadTimeDays: 21,
        materials: ['Glass Tesserae', 'Natural Stone', 'Cement'],
        dimensions: { width: 40, height: 30, depth: 2 },
        weight: 3.5,
        allowsCustomization: true,
        customizationOptions: {
            sizes: ['30x20cm', '40x30cm', '60x45cm'],
            notes: 'Custom size and framing available.',
        },
        isActive: true,
        isFeatured: true,
        rating: 4.9,
        reviewCount: 7,
        salesCount: 14,
        viewCount: 520,
    },
    {
        artisan: artisan2._id,
        collectionId: collection2._id,
        title: 'Mosaic Decorative Tray',
        description: 'A stunning decorative tray with geometric mosaic patterns inspired by ancient Jordanian architecture. Functional and beautiful.',
        price: 75,
        category: 'فسيفساء',
        tags: ['tray', 'mosaic', 'geometric', 'decor', 'jordan'],
        images: ['https://placehold.co/600x600?text=Mosaic+Tray'],
        thumbnailIndex: 0,
        productType: 'ready-made',
        stock: 3,
        materials: ['Wood Base', 'Ceramic Tiles', 'Grout'],
        dimensions: { width: 35, height: 4, depth: 25 },
        weight: 1.2,
        allowsCustomization: false,
        isActive: true,
        isFeatured: false,
        rating: 4.6,
        reviewCount: 5,
        salesCount: 9,
        viewCount: 180,
    },
    {
        artisan: artisan3._id,
        collectionId: collection3._id,
        title: 'Traditional Embroidered Cushion Cover',
        description: 'A richly embroidered cushion cover featuring traditional Jordanian cross-stitch patterns. Each stitch is done by hand using high-quality linen thread.',
        price: 38,
        category: 'تطريز ونسيج',
        tags: ['embroidery', 'cushion', 'traditional', 'linen', 'handmade'],
        images: ['https://placehold.co/600x600?text=Embroidered+Cushion'],
        thumbnailIndex: 0,
        productType: 'ready-made',
        stock: 12,
        materials: ['Linen', 'Cotton Thread', 'Silk Accent'],
        dimensions: { width: 45, height: 1, depth: 45 },
        weight: 0.3,
        allowsCustomization: true,
        customizationOptions: {
            colors: ['Red & Black', 'Blue & White', 'Green & Gold'],
            notes: 'Custom color combinations or pattern requests welcome.',
        },
        isActive: true,
        isFeatured: true,
        rating: 4.5,
        reviewCount: 8,
        salesCount: 30,
        viewCount: 290,
    },
    {
        artisan: artisan1._id,
        title: 'Ceramic Wall Plaque - Arabic Calligraphy',
        description: 'A hand-painted ceramic plaque featuring classical Arabic calligraphy. A meaningful gift or statement piece for any home.',
        price: 55,
        category: 'فخار وخزف',
        tags: ['calligraphy', 'ceramic', 'plaque', 'arabic', 'gift'],
        images: ['https://placehold.co/600x600?text=Calligraphy+Plaque'],
        thumbnailIndex: 0,
        productType: 'made-to-order',
        leadTimeDays: 14,
        materials: ['Ceramic', 'Hand-painted Glaze'],
        dimensions: { width: 25, height: 1, depth: 25 },
        weight: 0.5,
        allowsCustomization: true,
        customizationOptions: {
            engravingAllowed: false,
            notes: 'Custom text or quotes can be painted on request.',
        },
        isActive: true,
        isFeatured: false,
        rating: 4.7,
        reviewCount: 6,
        salesCount: 11,
        viewCount: 155,
    },
]);

await OriginStory.insertMany([
    {
        product: p1._id,
        artisan: artisan1._id,
        origin: {
            region: 'Amman',
            village: 'Wadi Al-Seer',
            coordinates: { lat: 31.9539, lng: 35.9106 },
        },
        craftingProcess: 'Each bowl begins as a raw block of locally sourced clay from the Jordan Valley. It is wedged by hand to remove air pockets, then centered and thrown on a manual kick wheel. After the initial form is shaped, it is left to dry for 24 hours before trimming the foot ring. A first bisque firing occurs at 900C, followed by hand-painting of the natural glaze, then a final glaze firing at 1200C.',
        materialsSource: 'Clay is sourced from the Jordan Valley. Glazes are prepared in-studio using natural mineral oxides imported from Turkey, combined with locally collected ash for matte finishes.',
        culturalSignificance: 'Pottery has been central to Jordanian daily life for thousands of years. Vessels like this bowl were used in ancient Nabataean and Roman settlements across the region. This work honors those roots while bringing them into modern homes.',
        artisanPersonalNote: 'This bowl was inspired by the colors I see on my morning walks through Wadi Al-Seer. The desert at sunrise has a warmth I try to capture in every piece.',
        estimatedCraftingTime: '3 to 4 days including drying and firing',
        generationsTaught: 'Self-taught, then refined under master potter Ibrahim Al-Asmar for 3 years.',
        certIsVisible: true,
    },
    {
        product: p3._id,
        artisan: artisan2._id,
        origin: {
            region: 'Madaba',
            village: 'Madaba City',
            coordinates: { lat: 31.7176, lng: 35.7932 },
        },
        craftingProcess: 'The mosaic begins with a scaled sketch of the original Madaba Map composition. Glass tesserae are cut by hand using a hammer and hardie, then laid individually onto a fiberglass mesh using traditional lime-based adhesive. The panel is grouted with white cement mixed with pigment, then polished to reveal the final design. The process requires over 40 hours of skilled work.',
        materialsSource: 'Glass tesserae are sourced from Murano, Italy and from local Jordanian manufacturers in Madaba. Natural stone pieces come from the Jordanian highlands. The wooden frame is crafted by a local carpenter in the same workshop.',
        culturalSignificance: 'The Madaba Map, discovered in 1884, is the oldest surviving cartographic depiction of the Holy Land. By recreating it in mosaic, this heritage is preserved and introduced to new generations and visitors from around the world.',
        artisanPersonalNote: 'My grandfather worked on restoring the original Madaba Map mosaic in the 1960s. This craft is in my blood.',
        estimatedCraftingTime: '3 to 4 weeks for a standard 40x30cm panel',
        generationsTaught: 'Third generation mosaic artist. Learned from father Mansour, who learned from grandfather Yousef.',
        certIsVisible: true,
    },
]);

const order1 = await Order.create({
    customer: customer1._id,
    items: [
        {
            product: p1._id,
            artisan: artisan1._id,
            title: p1.title,
            price: p1.price,
            quantity: 2,
            image: p1.images[0],
        },
        {
            product: p5._id,
            artisan: artisan3._id,
            title: p5.title,
            price: p5.price,
            quantity: 1,
            image: p5.images[0],
        },
    ],
    subtotal: 94,
    shippingCost: 3,
    discount: 0,
    totalAmount: 97,
    shippingAddress: {
        recipientName: 'Lara Khalid',
        phone: '0791234567',
        city: 'Amman',
        governorate: 'Amman',
        street: 'Al-Madeena St, Building 12',
        notes: 'Leave at door if no answer.',
    },
    paymentMethod: 'stripe',
    paymentStatus: 'paid',
    paymentIntentId: 'pi_seed_test_001',
    status: 'delivered',
});

const order2 = await Order.create({
    customer: customer2._id,
    items: [
        {
            product: p3._id,
            artisan: artisan2._id,
            title: p3.title,
            price: p3.price,
            quantity: 1,
            image: p3.images[0],
        },
    ],
    subtotal: 185,
    shippingCost: 5,
    discount: 0,
    totalAmount: 190,
    shippingAddress: {
        recipientName: 'Omar Nasser',
        phone: '0797654321',
        city: 'Irbid',
        governorate: 'Irbid',
        street: 'University Street, Apt 3',
    },
    paymentMethod: 'cash_on_delivery',
    paymentStatus: 'pending',
    status: 'confirmed',
});

await Review.insertMany([
    {
        reviewer: customer1._id,
        product: p1._id,
        artisan: artisan1._id,
        order: order1._id,
        rating: 5,
        title: 'Absolutely stunning piece!',
        body: 'The clay bowl exceeded my expectations. The color, weight, and finish are all perfect. Fatima clearly puts so much care into her work. Will definitely order again.',
        subRatings: { quality: 5, accuracy: 5, shipping: 5, communication: 5 },
        isVerifiedPurchase: true,
        isVisible: true,
        helpfulVotes: 8,
        artisanReply: {
            content: 'Thank you so much, Lara! It was a joy to make this for you. I hope it brings warmth to your home.',
            repliedAt: new Date(),
        },
    },
    {
        reviewer: customer1._id,
        product: p5._id,
        artisan: artisan3._id,
        order: order1._id,
        rating: 4,
        title: 'Beautiful craftsmanship',
        body: 'The embroidery is incredibly detailed and the colors are vibrant. It took a bit longer than expected to arrive but the quality was worth the wait.',
        subRatings: { quality: 5, accuracy: 4, shipping: 3, communication: 4 },
        isVerifiedPurchase: true,
        isVisible: true,
        helpfulVotes: 3,
    },
]);

const workshopSession1 = await WorkshopSession.create({
    artisan: artisan1._id,
    title: 'Introduction to Hand-Thrown Pottery',
    description: 'Learn the basics of centering clay, opening, and pulling walls on the pottery wheel. All materials provided. Suitable for complete beginners.',
    category: 'Pottery',
    coverImage: 'https://placehold.co/800x400?text=Pottery+Workshop',
    locationType: 'physical',
    location: {
        address: 'Wadi Al-Seer Studio, Building 5',
        city: 'Amman',
        governorate: 'Amman',
        coordinates: { lat: 31.9539, lng: 35.9106 },
    },
    schedule: {
        date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        startTime: '10:00',
        endTime: '13:00',
        durationMins: 180,
    },
    capacity: 8,
    bookedCount: 1,
    price: 35,
    includes: ['All clay and tools', 'Firing of one finished piece', 'Light refreshments'],
    requirements: ['Wear clothes you do not mind getting dirty', 'Closed-toe shoes'],
    skillLevel: 'beginner',
    status: 'upcoming',
});

const workshopSession2 = await WorkshopSession.create({
    artisan: artisan3._id,
    title: 'Traditional Jordanian Embroidery Workshop',
    description: 'Discover the beauty of tatreez — traditional Palestinian and Jordanian cross-stitch embroidery. You will complete a small embroidered panel to take home.',
    category: 'Embroidery',
    coverImage: 'https://placehold.co/800x400?text=Embroidery+Workshop',
    locationType: 'physical',
    location: {
        address: 'Karak Cultural Center, Hall B',
        city: 'Karak',
        governorate: 'Karak',
        coordinates: { lat: 31.1835, lng: 35.7043 },
    },
    schedule: {
        date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
        startTime: '14:00',
        endTime: '17:00',
        durationMins: 180,
    },
    capacity: 12,
    bookedCount: 1,
    price: 25,
    includes: ['Embroidery hoop and needle', 'Thread kit', 'Pattern guide sheet'],
    requirements: ['No experience needed'],
    skillLevel: 'beginner',
    status: 'upcoming',
});

await WorkshopBooking.insertMany([
    {
        session: workshopSession1._id,
        customer: customer1._id,
        participants: 1,
        totalPrice: 35,
        paymentStatus: 'paid',
        paymentIntentId: 'pi_seed_workshop_001',
        status: 'confirmed',
    },
    {
        session: workshopSession2._id,
        customer: customer2._id,
        participants: 1,
        totalPrice: 25,
        paymentStatus: 'pending',
        status: 'confirmed',
    },
]);

console.log('Database seeded successfully.');
console.log('Admin     → admin@souqjo.com   / Password123!');
console.log('Customer  → lara@example.com   / Password123!');
console.log('Customer  → omar@example.com   / Password123!');
console.log('Artisan   → fatima@example.com / Password123!');
console.log('Artisan   → khalil@example.com / Password123!');
console.log('Artisan   → nour@example.com   / Password123!');

await mongoose.disconnect();